title: ""
author: "Ethan Cohen"
description: <p align="center"> <img width="90" height="90" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/University_of_Minnesota_Logo.svg/1024px-University_of_Minnesota_Logo.svg.png?20200121234844"></p>University of Minnesota
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {url: "/files/cv/ECohen_CV_2023.pdf", title: "CV"}
  - {file: "research.md" , title: "Research"}
  - {file: "posts.md", title: "Posts"}
#  - {file: "teaching.md" , title: "Teaching"}
#  - {file: "blog.md" , title: "Blog"}
#  - {file: "resources.md" , title: "Resources"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:cohen.ethant@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/ettcohen"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/e-t-cohen/"}
 # - {title: Twitter, icon: twitter, url: "https://twitter.com/LaDelgadoP"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
