project:
  type: website
  output-dir: docs


resources:
    - "files/**"
    - "css/**"

website:
  title: "Ethan Cohen"
  navbar:
    pinned: true

    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: files/cv/ethan-cohen-cv.pdf
      - text: "Research"
        href: research.qmd

  page-footer:
    left: |
      [![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/University_of_Minnesota_Logo.svg/1024px-University_of_Minnesota_Logo.svg.png?20200121234844){fig-alt="UMN" width=65px}](https://cla.umn.edu/economics)
      <a href="https://cla.umn.edu/economics" style="text-decoration:none">University of Minnesota</a>

format:
  html:
    theme: cosmo
    max-width: 500px
    css: css/styles.css
    toc: false

filters:
  - auto-dark


